name: Variables
on:
  workflow_dispatch:
  
jobs:
  build-main:
    if: github.ref_name == 'main'
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  build-all: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          echo branch ${{ github.ref_name }}
          echo branch $GITHUB_REF_NAME

      - name: Run a multi-line script
        if: env.GITHUB_REF_NAME == 'main'
        run: |
          echo branch $GITHUB_REF_NAME
          echo Add other actions to build,
          echo test, and deploy your project.
